env:
  browser: true
  node: true
  es2022: true
extends:
  - eslint:recommended
overrides:
  - files:
    - src/tests/**/*.js
    env: {jest: true}
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  comma-spacing:
    - error
  no-unused-vars:
    - error
    - args: none
  comma-dangle:
    - error
    - always-multiline
  eol-last:
    - error
    - always
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  no-trailing-spaces:
    - error
  object-curly-spacing:
    - error
    - never
  prefer-const:
    - error
    - destructuring: all
  quotes:
    - error
    - single
  quote-props:
    - error
  semi:
    - error
    - always
